### ISSUE TITLE
where is the consensus?

### ISSUE THREAD

**Issue by xiezy0** [AnthonyXuan/chain-pdp#1]

**Comment by AnthonyXuan** [comment]
Maybe you should try to adapt PBFT or other consensus mechanism, you may fork this repo and send a pull request. :)

**Comment by xiezy0** [comment]
can chang-chain use in your project??

**Comment by AnthonyXuan** [comment]
I've never heard of the chang-chain project. You can provide your link to me.

**Comment by xiezy0** [comment]
why you close my issue？If i leave harbin i will open the link。

**Comment by AnthonyXuan** [comment]
I will let him notice your disloyalty.
